### ISSUE TITLE
Can't perform pod init when using the template

### ISSUE THREAD

**Issue by Ysix** [OMTS/XcodeTemplates#3]
error message:

```RuntimeError - [Xcodeproj] Type checking error: got `PBXSourcesBuildPhase` for attribute: Attribute `buildPhases` (type: `to_many`, classes: `["PBXCopyFilesBuildPhase", "PBXShellScriptBuildPhase"]`, owner class: `PBXAggregateTarget`)```

**Comment by imanzarrabian** [comment]
@Ysix  fixed in 2779aa4ac98deddc91e848cd1c7ec4e28885ae21
